let conditions = {
  canSurrenderAfterSplit: true,
  canDoubleForLess: true,
  canDoubleAfterSplit: true,
  canDoubleOn10or11Only: true,
  canDoubleAnyTwo: true,
  canDoubleSplitAces: true,
  canSurrender: true,
  canSplitForLess: true,
  dealerStaysOnSoft17: true,
  decksPerShoe: 5,
  seatsPerTable: 7,
  minimumBet: 10,
  maximumBet: 100,
  startingBankroll: 100,
  canInsureForLess: true,
  shufflePoint: .75,
  // timeForBetting: 10,
  // dealTime: 5,
  // insuranceTime: 10,
  timeAfterPayout: 5000,
  welcomeMessage: 'Welcome to Black Jack 1984! Place bets with bet({seat id}, {amount}), deal with deal() or at any time use help()!',
  dealerHasBlackjack: 'Dealer has BlackJack! This hand is over!',
  insuranceMessage: 'Close insurance with closeIns() or take insurance with ins({seat id})!',
  placeBetsMessage: 'Change bet with bet({seat id}, {amount}) or deal with deal()!',
  handWinsMessage: ' ++',
  handLosesMessage: ' XX',
  handPushesMessage: ' 00',
  handSurrendersMessage: ' X0'
}